/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSubjectIdRouteRouteImport } from './routes/subject/$subjectId/route'
import { Route as SubjectSubjectIdIndexRouteImport } from './routes/subject/$subjectId/index'
import { Route as SubjectSubjectIdLectureLectureIdRouteImport } from './routes/subject/$subjectId/lecture/$lectureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRouteRoute = SubjectSubjectIdRouteRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdIndexRoute = SubjectSubjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectSubjectIdRouteRoute,
} as any)
const SubjectSubjectIdLectureLectureIdRoute =
  SubjectSubjectIdLectureLectureIdRouteImport.update({
    id: '/lecture/$lectureId',
    path: '/lecture/$lectureId',
    getParentRoute: () => SubjectSubjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteRouteWithChildren
  '/subject/$subjectId/': typeof SubjectSubjectIdIndexRoute
  '/subject/$subjectId/lecture/$lectureId': typeof SubjectSubjectIdLectureLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdIndexRoute
  '/subject/$subjectId/lecture/$lectureId': typeof SubjectSubjectIdLectureLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteRouteWithChildren
  '/subject/$subjectId/': typeof SubjectSubjectIdIndexRoute
  '/subject/$subjectId/lecture/$lectureId': typeof SubjectSubjectIdLectureLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subject/$subjectId'
    | '/subject/$subjectId/'
    | '/subject/$subjectId/lecture/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/subject/$subjectId' | '/subject/$subjectId/lecture/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/subject/$subjectId'
    | '/subject/$subjectId/'
    | '/subject/$subjectId/lecture/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectSubjectIdRouteRoute: typeof SubjectSubjectIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId/': {
      id: '/subject/$subjectId/'
      path: '/'
      fullPath: '/subject/$subjectId/'
      preLoaderRoute: typeof SubjectSubjectIdIndexRouteImport
      parentRoute: typeof SubjectSubjectIdRouteRoute
    }
    '/subject/$subjectId/lecture/$lectureId': {
      id: '/subject/$subjectId/lecture/$lectureId'
      path: '/lecture/$lectureId'
      fullPath: '/subject/$subjectId/lecture/$lectureId'
      preLoaderRoute: typeof SubjectSubjectIdLectureLectureIdRouteImport
      parentRoute: typeof SubjectSubjectIdRouteRoute
    }
  }
}

interface SubjectSubjectIdRouteRouteChildren {
  SubjectSubjectIdIndexRoute: typeof SubjectSubjectIdIndexRoute
  SubjectSubjectIdLectureLectureIdRoute: typeof SubjectSubjectIdLectureLectureIdRoute
}

const SubjectSubjectIdRouteRouteChildren: SubjectSubjectIdRouteRouteChildren = {
  SubjectSubjectIdIndexRoute: SubjectSubjectIdIndexRoute,
  SubjectSubjectIdLectureLectureIdRoute: SubjectSubjectIdLectureLectureIdRoute,
}

const SubjectSubjectIdRouteRouteWithChildren =
  SubjectSubjectIdRouteRoute._addFileChildren(
    SubjectSubjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectSubjectIdRouteRoute: SubjectSubjectIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
